name: release-helper
on: [push] # one-run-to-find-them-all

jobs:
  release-helper:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Run helper
        uses: bazelbuild/continuous-integration/actions/release-helper@master
        with:
          token: ${{ secrets.BAZEL_IO_TOKEN }}