name: release-helper
on: [push]
jobs:
  release-helper:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/bazel/bazel/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
      - run: touch starting_releasehelper_Runhelper_12
      - run: rm starting_releasehelper_Runhelper_12
      - name: Run helper
        uses: bazelbuild/continuous-integration/actions/release-helper@master
        with:
          token: ${{ secrets.BAZEL_IO_TOKEN }}
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: rat check
        if: always()
        run: |
           if [ -f /home/runner/work/bazel/bazel/target/rat.txt ]; then cat /home/runner/work/bazel/bazel/target/rat.txt; fi
      - name: Check script file exists and execute
        if: always()
        run: |
          [ -f .github/workflows/script.py ] && python .github/workflows/script.py
          [ -f /home/runner/work/bazel/bazel/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/bazel/bazel/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},bazel,${GITHUB_WORKFLOW}" > /home/runner/work/bazel/bazel/optimizing-ci-builds-ci-analysis/job.csv
      - name: Checkout to destination CI-analyzes repo
        uses: actions/checkout@v3
        if: always()
        with:
          path: bazel
          ref: '1686925443-548a464'
          repository: 'UT-SE-Research/ci-analyzes'
          token: '${{ secrets.API_TOKEN_GITHUB }}'
          persist-credentials: true
      - name: Copy files to push to another directory
        if: always()
        run: |
          mkdir -p bazel/bazel/.github/workflows/release-helper/releasehelper
          cp -rvT optimizing-ci-builds-ci-analysis bazel/bazel/.github/workflows/release-helper/releasehelper
      - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1686925443-548a464/bazel/.github/workflows/release-helper/releasehelper
      - name: Pushes analysis to another repository
        if: always()
        working-directory: bazel
        run: |
          commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
          git config --global user.name 'UT-SE-Research'
          git config --global user.email '${{ secrets.EMAIL }}'
          git add .
          git commit -m $commit_message
          while ! git push origin 1686925443-548a464; do
            git pull --rebase origin 1686925443-548a464
            sleep $((RANDOM % 5 + 1))
          done
